# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
ersion: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: beevelop/android:latest
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: System information
          command: |
            mkdir $ANDROID_HOME/licenses
            echo [ANDROID_SDK_LICENSE] >> $ANDROID_HOME/licenses/android-sdk-license
            echo y | android update sdk --no-ui --all --filter "build-tools-25.0.2"
            echo y | android update sdk --no-ui --all --filter "extra-android-m2repository,extra-google-m2repository"
#      - run:
#          name: Install dependencies
#          command: ./gradlew androidDependencies
#      - run:
#          name: Build
#          command: ./gradlew assembleRelease
